#datasource
spring.datasource.url=jdbc:postgresql://ep-young-scene-asuqpj9f.c-4.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_0Uo1ZHYdtpyT
#jpa
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
#swagger
springdoc.swagger-ui.path=/test
#key
jwt.secret=key
#you email
spring.mail.username=suerovm2@gmail.com
#you password
spring.mail.password=gnrpfwbnugydwndf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
